[book]
title = "Rust for Linux"
author = "Rust for Linux Contributors"
description = "Adding support for the Rust language to the Linux kernel"
language = "en"

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/Rust-for-Linux/rust-for-linux.com"
edit-url-template = ""
no-section-label = true

[output.html.redirect]
"/pinned-init" = "/pin-init"
"/pinned-init.html" = "/pin-init"

[output.html.fold]
enable = true
level = 0
